# This is a basic workflow to help you get started with Actions

name: SAupload

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # upload to SA
      - name: Azure Blob Storage Upload
        # You may pin to the exact commit or the version.
        # uses: bacongobbler/azure-blob-storage-upload@779a18b594a1a7cf5412645e06c856324a8b01e5
        uses: bacongobbler/azure-blob-storage-upload@v1.1.1
        with:
          # The connection string for the storage account
          connection_string: 'https://tccc-edge-mba-qa-blob-01.azureedge.net/?sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2022-05-17T16:51:35Z&st=2022-05-17T08:51:35Z&spr=https&sig=Svrc%2B8uRzVsgbX2q0YSpIhQIqj4o3LVJVjnhVic548w%3D'
          # The name of the storage account container these assets will be uploaded to
          container_name: test
          # The name of the directory you want to upload
          source_dir: proba.txt
          # Extra arguments that can be passed to `az storage blob upload-batch|sync`. Useful for passing flags like `--pattern` or `--destination-path`
          extra_args: # optional
          # Use `az storage blob sync` to synchronize blobs recursively
          sync: # optional
