# This is a basic workflow to help you get started with Actions

name: SAupload

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Azure Blob Upload
        # You may pin to the exact commit or the version.
        # uses: LanceMcCarthy/Action-AzureBlobUpload@afa19a0653e11c5e1ae9b3e4e1c44663bfbde935
        uses: LanceMcCarthy/Action-AzureBlobUpload@v1.11.0
        with:
          # Azure Storage ConnectionString for the container (Azure Portal - select Storage Account - Access Keys blade).
          connection_string: 'BlobEndpoint=https://sause2tcccmbaqa0001.blob.core.windows.net/;QueueEndpoint=https://sause2tcccmbaqa0001.queue.core.windows.net/;FileEndpoint=https://sause2tcccmbaqa0001.file.core.windows.net/;TableEndpoint=https://sause2tcccmbaqa0001.table.core.windows.net/;SharedAccessSignature=sv=2020-08-04&ss=bfqt&srt=sco&sp=rwdlacupitfx&se=2022-05-17T16:51:35Z&st=2022-05-17T08:51:35Z&spr=https&sig=Svrc%2B8uRzVsgbX2q0YSpIhQIqj4o3LVJVjnhVic548w%3D'
          # Blob Container name (e.g. my-container).
          container_name: test
          # The local folder containing all the files and subfolders to upload to the blob container (use a trailing slash)
          source_folder: \
          # The target folder to use in the blob container with (do not use a leading or trailing slash)
          destination_folder: # optional
          # This option will delete all the blobs in destination_folder before uploading the new files
          clean_destination_folder: # optional
          # If you want the Action to fail and report an error if the source_folder is empty.
          fail_if_source_empty: # optional
          # Set to false if you want all subfolders ignored.
          is_recursive: # optional, default is true

        
